import Link from 'next/link';

export default function PrivacyPage() {
  return (
    <main className="min-h-screen bg-white dark:bg-gray-950 flex flex-col">
      <nav className="border-b border-gray-200 dark:border-gray-800 px-6 py-4 flex items-center justify-between">
        <Link href="/" className="text-xl font-bold text-brand-600 dark:text-brand-400">
          QiFlow
        </Link>
        <div className="flex items-center gap-4">
          <Link href="/auth/login" className="text-sm text-gray-600 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white transition-colors">
            Log in
          </Link>
          <Link href="/auth/register" className="text-sm bg-brand-600 hover:bg-brand-700 text-white px-4 py-2 rounded-lg transition-colors">
            Get started
          </Link>
        </div>
      </nav>

      <div className="max-w-3xl mx-auto px-6 py-16 flex-1">
        <h1 className="text-4xl font-bold text-gray-900 dark:text-white mb-6">Privacy Policy</h1>
        <p className="text-sm text-gray-500 dark:text-gray-400 mb-8">Last Updated: August 19, 2026</p>

        <div className="space-y-6 text-gray-700 dark:text-gray-300 text-sm leading-relaxed">
          <section className="space-y-2">
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white">1. Information We Collect</h2>
            <p>
              QiFlow collects minimal data required to provide payment gateway services:
            </p>
            <ul className="list-disc pl-5 space-y-1 text-gray-600 dark:text-gray-400">
              <li>Merchant email addresses and hashed passwords.</li>
              <li>Public Quai Network wallet addresses associated with payment sessions.</li>
              <li>Transaction metadata (amount, session status, timestamps).</li>
            </ul>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white">2. API Key Storage & Security</h2>
            <p>
              API keys generated by merchants are displayed only once upon creation. QiFlow stores only one-way SHA-256 cryptographic hashes of API keys to prevent exposure.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white">3. Public Blockchain Data</h2>
            <p>
              Payments processed via QiFlow are broadcast to the public Quai Network. Blockchain transaction hashes, wallet addresses, and smart contract executions are publicly queryable on the Quai ledger.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white">4. Data Retention & Sharing</h2>
            <p>
              We do not sell or monetize personal data. Information is retained solely for account administration, dispute resolution, and audit logs.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-xl font-semibold text-gray-900 dark:text-white">5. Contact Us</h2>
            <p>
              For privacy inquiries or account data requests, please contact the QiFlow team.
            </p>
          </section>
        </div>
      </div>

      <footer className="border-t border-gray-200 dark:border-gray-800 px-6 py-8 text-center text-sm text-gray-400 flex flex-col sm:flex-row items-center justify-between max-w-5xl mx-auto w-full">
        <span>© {new Date().getFullYear()} QiFlow. MIT License.</span>
        <div className="flex gap-4 mt-2 sm:mt-0">
          <Link href="/terms" className="hover:underline">Terms of Service</Link>
          <Link href="/privacy" className="hover:underline">Privacy Policy</Link>
        </div>
      </footer>
    </main>
  );
}
